name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y zlib1g-dev
        sudo apt-get install -y libjpeg-dev
        sudo apt-get install -y libfreetype6-dev
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y libssl-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install -r requirements.txt
    
    - name: Configure buildozer
      run: |
        buildozer init
        echo "android.sdk_path = /opt/android-sdk" >> buildozer.spec
        echo "android.ndk_path = /opt/android-ndk" >> buildozer.spec
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: /opt/android-sdk
        ANDROID_NDK_HOME: /opt/android-ndk
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: bingo-educativo.apk
        path: bin/*.apk
