name: Build APK Simple
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        pip install buildozer
        pip install kivy==2.3.1 kivymd==1.2.0 pillow requests pyjnius
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bingo-educativo.apk
        path: bin/*.apk
      if: always()
