name: Build APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y zlib1g-dev libjpeg-dev libfreetype6-dev libffi-dev libssl-dev
        sudo apt-get install -y git unzip wget
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install kivy==2.3.1 kivymd==1.2.0 pillow requests pyjnius
    
    - name: Configure environment
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        echo "ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/home/runner/.buildozer/android/platform/android-ndk" >> $GITHUB_ENV
    
    - name: Initialize buildozer
      run: |
        buildozer init
        # Aceptar licencias automáticamente
        echo "y" | buildozer android debug || true
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: bingo-educativo.apk
        path: bin/*.apk
      if: always()
